import{a as p,S as E,i as n}from"./assets/vendor-BK_rxH-O.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const a of i.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&r(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function r(e){if(e.ep)return;e.ep=!0;const i=t(e);fetch(e.href,i)}})();const I="51718020-504e1b86ae47f9489a580fda2",M="https://pixabay.com/api/";p.defaults.baseURL=M;function f(o,s=1,t=15){return p.get("",{params:{key:I,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:t}}).then(r=>r.data).catch(r=>{throw r})}const h=document.getElementById("gallery"),d=document.getElementById("loader"),g=document.getElementById("load-more"),P=new E(".gallery a",{captionsData:"alt",captionDelay:200});function y(o){const s=o.map(({webformatURL:t,largeImageURL:r,tags:e,likes:i,views:a,comments:w,downloads:B})=>`
      <li class="card">
        <a href="${r}">
          <img src="${t}" alt="${$(e)}" loading="lazy" />
        </a>
        <div class="meta">
          <span>Likes: ${i}</span>
          <span>Views: ${a}</span>
          <span>Comments: ${w}</span>
          <span>Downloads: ${B}</span>
        </div>
      </li>
    `).join("");h.insertAdjacentHTML("beforeend",s),P.refresh()}function R(){h.innerHTML=""}function L(){d.classList.add("is-visible"),d.setAttribute("aria-hidden","false")}function b(){d.classList.remove("is-visible"),d.setAttribute("aria-hidden","true")}function A(){g.classList.remove("is-hidden")}function v(){g.classList.add("is-hidden")}function $(o=""){return String(o).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}const m=document.getElementById("search-form"),D=document.getElementById("load-more");let c="",l=1,u=0;m.addEventListener("submit",async o=>{if(o.preventDefault(),c=(new FormData(m).get("search-text")||"").trim(),!c){n.warning({title:"Упс…",message:"Введіть пошукове слово.",timeout:2500,position:"topRight"});return}l=1,R(),v(),L();try{const t=await f(c,l),r=Array.isArray(t==null?void 0:t.hits)?t.hits:[];if(u=(t==null?void 0:t.totalHits)||0,r.length===0){n.info({title:"Немає збігів",message:"Sorry, there are no images matching your search query. Please try again!",timeout:3e3,position:"topRight"});return}y(r),u>r.length&&A()}catch{n.error({title:"Помилка",message:"Сталася помилка під час запиту. Спробуйте пізніше.",timeout:3e3,position:"topRight"})}finally{b()}});D.addEventListener("click",async()=>{l+=1,L(),v();try{const o=await f(c,l),s=Array.isArray(o==null?void 0:o.hits)?o.hits:[];y(s);const t=Math.ceil(u/15);l>=t?n.info({message:"We're sorry, but you've reached the end of search results.",timeout:3e3,position:"topRight"}):A();const{height:r}=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}catch{n.error({title:"Помилка",message:"Не вдалося завантажити більше зображень.",timeout:3e3,position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
