import{a as p,S as I,i as a}from"./assets/vendor-BK_rxH-O.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const n of s.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&r(n)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();const P="51718020-504e1b86ae47f9489a580fda2",R="https://pixabay.com/api/";p.defaults.baseURL=R;async function h(i,o=1,t=15){try{return(await p.get("",{params:{key:P,q:i,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:t}})).data}catch(r){throw r}}const f=document.getElementById("gallery"),u=document.getElementById("loader"),g=document.getElementById("load-more"),M=new I(".gallery a",{captionsData:"alt",captionDelay:200});function y(i){const o=i.map(({webformatURL:t,largeImageURL:r,tags:e,likes:s,views:n,comments:B,downloads:E})=>`
      <li class="card">
        <a href="${r}">
          <img src="${t}" alt="${D(e)}" loading="lazy" />
        </a>
        <div class="meta">
          <span>Likes: ${s}</span>
          <span>Views: ${n}</span>
          <span>Comments: ${B}</span>
          <span>Downloads: ${E}</span>
        </div>
      </li>
    `).join("");f.insertAdjacentHTML("beforeend",o),M.refresh()}function $(){f.innerHTML=""}function L(){u.classList.add("is-visible"),u.setAttribute("aria-hidden","false")}function b(){u.classList.remove("is-visible"),u.setAttribute("aria-hidden","true")}function A(){g.classList.remove("is-hidden")}function v(){g.classList.add("is-hidden")}function D(i=""){return String(i).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}const m=document.getElementById("search-form"),q=document.getElementById("load-more");let d="",l=1,w=0;const c=15;m.addEventListener("submit",async i=>{if(i.preventDefault(),d=(new FormData(m).get("search-text")||"").trim(),!d){a.warning({title:"Упс…",message:"Введіть пошукове слово.",timeout:2500,position:"topRight"});return}l=1,$(),v(),L();try{const t=await h(d,l,c),r=Array.isArray(t==null?void 0:t.hits)?t.hits:[];if(w=(t==null?void 0:t.totalHits)||0,r.length===0){a.info({title:"Немає збігів",message:"Sorry, there are no images matching your search query. Please try again!",timeout:3e3,position:"topRight"});return}y(r),r.length<c?a.info({message:"We're sorry, but you've reached the end of search results.",timeout:3e3,position:"topRight"}):A()}catch{a.error({title:"Помилка",message:"Сталася помилка під час запиту. Спробуйте пізніше.",timeout:3e3,position:"topRight"})}finally{b()}});q.addEventListener("click",async()=>{var i;l+=1,L(),v();try{const o=await h(d,l,c),t=Array.isArray(o==null?void 0:o.hits)?o.hits:[];y(t);const r=Math.ceil(w/c);l>=r||t.length<c?a.info({message:"We're sorry, but you've reached the end of search results.",timeout:3e3,position:"topRight"}):A();const{height:e}=((i=document.querySelector(".gallery li"))==null?void 0:i.getBoundingClientRect())||{height:0};e&&window.scrollBy({top:e*2,behavior:"smooth"})}catch{a.error({title:"Помилка",message:"Не вдалося завантажити більше зображень.",timeout:3e3,position:"topRight"})}finally{b()}});
//# sourceMappingURL=index.js.map
